/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        /* ── ADTS Clinical Authority Palette ── */
        'surface':                  '#f7f9ff',
        'surface-dim':              '#ccdcf0',
        'surface-bright':           '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#edf4ff',
        'surface-container':        '#e3efff',
        'surface-container-high':   '#daeafe',
        'surface-container-highest':'#d4e4f8',
        'on-surface':               '#0d1d2b',
        'on-surface-variant':       '#3f484b',
        'inverse-surface':          '#233241',
        'inverse-on-surface':       '#e8f1ff',
        'outline':                  '#6f797b',
        'outline-variant':          '#bec8cb',
        'surface-tint':             '#006876',
        'surface-variant':          '#d4e4f8',

        'primary':                  '#005460',
        'on-primary':               '#ffffff',
        'primary-container':        '#0a6e7c',
        'on-primary-container':     '#9feefe',
        'inverse-primary':          '#84d2e2',
        'primary-fixed':            '#a0efff',
        'primary-fixed-dim':        '#84d2e2',
        'on-primary-fixed':         '#001f25',
        'on-primary-fixed-variant': '#004e59',

        'secondary':                '#436085',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#b6d4ff',
        'on-secondary-container':   '#3e5b80',
        'secondary-fixed':          '#d3e4ff',
        'secondary-fixed-dim':      '#abc9f3',
        'on-secondary-fixed':       '#001c38',
        'on-secondary-fixed-variant':'#2a486c',

        'tertiary':                 '#005835',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#007347',
        'on-tertiary-container':    '#8ff6bb',
        'tertiary-fixed':           '#90f7bc',
        'tertiary-fixed-dim':       '#74daa1',
        'on-tertiary-fixed':        '#002111',
        'on-tertiary-fixed-variant':'#005231',

        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',

        'background':               '#f7f9ff',
        'on-background':            '#0d1d2b',
      },
      fontFamily: {
        'display':    ['DM Sans', 'sans-serif'],
        'headline':   ['DM Sans', 'sans-serif'],
        'body':       ['Inter', 'sans-serif'],
        'mono':       ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg':       ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile':['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md':      ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':          ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':          ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps':       ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono':        ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '400' }],
      },
      spacing: {
        'base':         '4px',
        'xs':           '8px',
        'sm':           '12px',
        'md':           '16px',
        'lg':           '24px',
        'xl':           '32px',
        'sidebar':      '240px',
        'gutter':       '16px',
        'margin-page':  '24px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg':      '0.5rem',
        'xl':      '0.75rem',
        'full':    '9999px',
      },
      boxShadow: {
        'clinical': '0 2px 4px rgba(28, 43, 58, 0.08)',
      },
    },
  },
  plugins: [],
};